# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: awscli
      directives:
        description: Install AWS CLI
      settings:
        id: Amazon.AWSCLI
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: docker
      directives:
        description: Install Docker Desktop
      settings:
        id: Docker.DockerDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotnet.10
      directives:
        description: Install .NET 10 SDK
      settings:
        id: Microsoft.DotNet.SDK.10
        source: winget
  
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        description: Install Git
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: neovim
      directives:
        description: Install NeoVim
      settings:
        id: Neovim.Neovim
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nodejs
      directives:
        description: Install Node.js
      settings:
        id: OpenJS.NodeJS
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell
      directives:
        description: Install PowerShell
      settings:
        id: Microsoft.PowerShell
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: claude
      directives:
        description: Install Claude Code
      settings:
        id: Anthropic.ClaudeCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: python
      directives:
        description: Install Python
      settings:
        id: Python.Python.3.14
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: codex
      directives:
        description: Install Codex
      settings:
        id: OpenAI.Codex
        source: winget
